[tool.poetry]
name = "pumpkin"
version = "0.1.0"
description = "The demoniac MAS monitoring platform. 🎃"
authors = ["Cédric Bonhomme <cedric@cedricbonhomme.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://sr.ht/~cedric/pumpkin"
repository = "https://git.sr.ht/~cedric/pumpkin"

[tool.poetry.dependencies]
python = "^3.10"
spade = "^3.2.2"

[tool.poetry.group.dev.dependencies]
mypy = "^0.982"
flake8 = "^5.0.4"
reorder-python-imports = "^3.9.0"
pre-commit = "^2.20.0"
black = "^22.10.0"
pyupgrade = "^3.2.0"
autoflake = "^1.7.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


keywords = ["MAS", "SPADE", "XMPP", "monitoring", "security"]

classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Security",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true

exclude = "build|dist|docs"
